### ISSUE TITLE
Game Additions

### ISSUE THREAD

**Issue by mithintv** [mithintv/horse-race#11]
### Tasks
- [x] End game w/ winning suit
- [x] Add decrement rungs
- [x] Have decrement rungs display their card when all horses reach threshold
- [x] Have decrement rungs push horses back
- [x] Run game w/o 'Click' button
