### ISSUE TITLE
Animations and Styling

### ISSUE THREAD

**Issue by mithintv** [mithintv/horse-race#13]
### Tasks
- [x] center game board
- [x] adjust layout to fit in full screen
- [x] shuffle deck on new game
- [x] add animations for horse movement
