### ISSUE TITLE
Reconfigure deck + rungs state

### ISSUE THREAD

**Issue by mithintv** [mithintv/horse-race#15]
### Tasks
- [x] shuffle deck upon game end
- [x] return new rungs upon game end
- [x] configure state for rungs in addition to deck
