### ISSUE TITLE
Game Summary

### ISSUE THREAD

**Issue by mithintv** [mithintv/horse-race#5]
### Game Summary
As a user, see the output summary of bets based on the winning suit 

### Tasks
- [x] Trigger end of game via a button
- [x] Create a Game Summary component
- [x] Display bets per player according to winning suit
- [x] Create a component to reset the game
