### ISSUE TITLE
Re-configure wager/bets data schema

### ISSUE THREAD

**Issue by mithintv** [mithintv/horse-race#7]
## Schema re-configuration
Currently, bets are updated through a reducer and stored via the context api. Re-configure the context api to make accessing bets more manageable for multiple bets per players as well as when delineating between winners and losers. 

### Tasks
- [x] Create sample dataset for quick access
- [x] Output current bets on Parameters
- [ ] Create numeric inputs for each individual wager
- [ ] Allow players to create multiple bets per suit
- [ ] Re-configure data schema for simple arithmetic for winning and losing bets
- [ ] Output new game summary
