### ISSUE TITLE
Add Cards and Basic Game

### ISSUE THREAD

**Issue by mithintv** [mithintv/horse-race#9]
### Tasks

- [x] Add Card component
- [x] Initialize 4 starting horses
- [x] Create random draw functionality
- [x] Have horses move based on suit of drawing card
